### PR TITLE
Remove dependency on ez_setup

### LINKED ISSUE #2: Cannot install via pip
I cannot install the package just uploaded to PyPI into a fresh virtualenv because it depends on `ez_setup` which is not installed:

```bash
$ python3.5 -m venv test_env
$ source test_env/bin/activate
(test_env) $ pip install bioprinter
Looking in indexes: https://pypi.org/simple
Collecting bioprinter
  Downloading https://pypi.org/packages/d9/3d/a823c9ad7b67b1b27029c1784afb2bf72a7d48827912fc0ac78f4c634fc8/bioprinter-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8rxmp23n/bioprinter/setup.py", line 1, in <module>
        import ez_setup
    ImportError: No module named 'ez_setup'
```

I can see that there's a local `ez_setup.py` in the repo, but either it's not being picked up by the import statement, or it is not mentinoned in the manifest file and has therefore not been bundled with the package on PyPI.

### PR DESCRIPTION
**Pull request by ecederstrand**
Fixes installation with pip. There's only one package in the repo, so just hardcode it in setup() instead of calling find_packages(). This removes the need for ez_setup.

Fixes #2

### CODE REVIEW

**Comment by Zulko** [comment]
The main purpose of ez_setup is to provide a custom "setup()" which allows for "develop mode" (``pip install -e``, or ``python setup.py install develop``). I have been using it for the last years but maybe there is a better solution today to get develop mode ? (does it come builtin with Python ?)

**Comment by Zulko** [comment]
Fixed with #2.

**Comment by ecederstrand** [comment]
`pip install -e .` works fine without `ez_setup.py` present. I just checked with:

```bash
git clone https://github.com/ecederstrand/bioprinter.git
cd bioprinter
git checkout patch-1
pip install -e .
```

But since my actual problem was solved by the new package, you're free to do whatever you want :-)

**Comment by Zulko** [comment]
The ez_setup.py file is a way of installing setuptools on computers which don't have setuptools.  The file is only required for users who have never installed setuptools before.

**Pull request closed without merging**
